name: authflow_example
description: Example app for the Authflow package
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  authflow:
    path: ../
  cupertino_icons: ^1.0.2
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
