name: authflow
description: "A flexible, provider-based authentication toolkit for Flutter with
  stream-based auth state, customizable storage, and composable UI widgets."
version: 1.0.1
homepage: https://github.com/vfiruz97/authflow
repository: https://github.com/vfiruz97/authflow
issue_tracker: https://github.com/vfiruz97/authflow/issues
topics: [authentication, login]
license: MIT

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0